"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
exports.__esModule = true;
var dynamodb_data_mapper_annotations_1 = require("@aws/dynamodb-data-mapper-annotations");
var Users = /** @class */ (function () {
    function Users() {
    }
    __decorate([
        dynamodb_data_mapper_annotations_1.autoGeneratedHashKey()
    ], Users.prototype, "UserID");
    __decorate([
        dynamodb_data_mapper_annotations_1.rangeKey()
    ], Users.prototype, "Username");
    __decorate([
        attribute()
    ], Users.prototype, "info");
    Users = __decorate([
        dynamodb_data_mapper_annotations_1.table('TestDB')
    ], Users);
    return Users;
}());
