import {
    autoGeneratedHashKey,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('TestDB')
class Users {
    @autoGeneratedHashKey()
    UserID: Number;
    
    @rangeKey()
    Username: String;

    @attribute()
    info: String
}